export const badges = [
  {
    name: "First Blood",
    description: "Complete your first lesson",
    icon: "trophy",
    unlockCondition: { type: "lesson_count", params: { count: 1 } },
    isSecret: false,
    category: "Milestone",
    order: 1,
  },
  {
    name: "Perfect Score",
    description: "Score 100% on any exercise",
    icon: "star",
    unlockCondition: { type: "perfect_exercise", params: {} },
    isSecret: false,
    category: "Achievement",
    order: 2,
  },
  {
    name: "Streak Warrior",
    description: "Maintain a 7-day learning streak",
    icon: "flame",
    unlockCondition: { type: "streak", params: { days: 7 } },
    isSecret: false,
    category: "Streak",
    order: 3,
  },
  {
    name: "Streak Legend",
    description: "Maintain an incredible 30-day learning streak",
    icon: "flame",
    unlockCondition: { type: "streak", params: { days: 30 } },
    isSecret: false,
    category: "Streak",
    order: 4,
  },
  {
    name: "Simulation Survivor",
    description: "Complete your first simulation",
    icon: "shield",
    unlockCondition: { type: "simulation_count", params: { count: 1 } },
    isSecret: false,
    category: "Simulation",
    order: 5,
  },
  {
    name: "Simulation Master",
    description: "Complete all 7 simulations across every chapter",
    icon: "award",
    unlockCondition: { type: "simulation_count", params: { count: 7 } },
    isSecret: false,
    category: "Simulation",
    order: 6,
  },
  {
    name: "Speed Demon",
    description: "Complete a lesson in under 5 minutes",
    icon: "zap",
    unlockCondition: { type: "speed_completion", params: { minutes: 5 } },
    isSecret: false,
    category: "Special",
    order: 7,
  },
  {
    name: "Night Owl",
    description: "Complete a lesson after 10 PM IST",
    icon: "moon",
    unlockCondition: { type: "time_of_day", params: { after: 22, before: 24 } },
    isSecret: false,
    category: "Special",
    order: 8,
  },
  {
    name: "Early Bird",
    description: "Complete a lesson before 7 AM IST",
    icon: "sun",
    unlockCondition: { type: "time_of_day", params: { after: 0, before: 7 } },
    isSecret: false,
    category: "Special",
    order: 9,
  },
  {
    name: "Quiz Whiz",
    description: "Achieve 5 perfect exercise scores in a row",
    icon: "target",
    unlockCondition: { type: "consecutive_perfect", params: { count: 5 } },
    isSecret: false,
    category: "Achievement",
    order: 10,
  },
  {
    name: "Comeback Kid",
    description: "Return after a broken streak and complete a lesson",
    icon: "heart",
    unlockCondition: { type: "comeback", params: {} },
    isSecret: false,
    category: "Special",
    order: 11,
  },
  {
    name: "Explorer",
    description: "Visit every section of the platform",
    icon: "compass",
    unlockCondition: { type: "explorer", params: {} },
    isSecret: false,
    category: "Milestone",
    order: 12,
  },
  {
    name: "Personality Unlocked",
    description: "Complete the money personality quiz",
    icon: "brain",
    unlockCondition: { type: "personality_quiz", params: {} },
    isSecret: false,
    category: "Special",
    order: 13,
  },
  {
    name: "Scam Spotter",
    description: "Achieve a perfect score on all Chapter 6 exercises",
    icon: "shield",
    unlockCondition: { type: "chapter_perfect", params: { chapter: 6 } },
    isSecret: false,
    category: "Chapter",
    order: 14,
  },
  {
    name: "Market Guru",
    description: "Achieve a perfect score on the Chapter 1 simulation",
    icon: "trending-up",
    unlockCondition: { type: "simulation_perfect", params: { chapter: 1 } },
    isSecret: false,
    category: "Chapter",
    order: 15,
  },
  {
    name: "Budget Boss",
    description: "Achieve a perfect score on the Chapter 4 simulation",
    icon: "coins",
    unlockCondition: { type: "simulation_perfect", params: { chapter: 4 } },
    isSecret: false,
    category: "Chapter",
    order: 16,
  },
  {
    name: "Debt Dodger",
    description: "Make all correct choices in the Chapter 5 simulation",
    icon: "shield",
    unlockCondition: { type: "simulation_perfect", params: { chapter: 5 } },
    isSecret: false,
    category: "Chapter",
    order: 17,
  },
  {
    name: "The Completionist",
    description: "Achieve 100% completion across everything on the platform",
    icon: "lock",
    unlockCondition: { type: "completionist", params: {} },
    isSecret: true,
    category: "Legendary",
    order: 18,
  },
  {
    name: "Social Learner",
    description: "Share your progress or certificate with others",
    icon: "share-2",
    unlockCondition: { type: "share", params: {} },
    isSecret: false,
    category: "Social",
    order: 19,
  },
  {
    name: "Money Mind",
    description:
      "Complete the personality quiz and earn badge-tier on the Chapter 3 simulation",
    icon: "brain",
    unlockCondition: { type: "money_mind", params: { chapter: 3 } },
    isSecret: false,
    category: "Chapter",
    order: 20,
  },
  {
    name: "Chapter 0 Graduate",
    description:
      "Complete all lessons, exercises, and simulation in 'What Even is Money?'",
    icon: "graduation-cap",
    unlockCondition: { type: "chapter_complete", params: { chapter: 0 } },
    isSecret: false,
    category: "Chapter",
    order: 21,
  },
  {
    name: "Chapter 1 Graduate",
    description:
      "Complete all lessons, exercises, and simulation in 'The Stock Market'",
    icon: "graduation-cap",
    unlockCondition: { type: "chapter_complete", params: { chapter: 1 } },
    isSecret: false,
    category: "Chapter",
    order: 22,
  },
  {
    name: "Chapter 2 Graduate",
    description:
      "Complete all lessons, exercises, and simulation in 'Investing 101'",
    icon: "graduation-cap",
    unlockCondition: { type: "chapter_complete", params: { chapter: 2 } },
    isSecret: false,
    category: "Chapter",
    order: 23,
  },
  {
    name: "Chapter 3 Graduate",
    description:
      "Complete all lessons, exercises, and simulation in 'Your Money Psychology'",
    icon: "graduation-cap",
    unlockCondition: { type: "chapter_complete", params: { chapter: 3 } },
    isSecret: false,
    category: "Chapter",
    order: 24,
  },
  {
    name: "Chapter 4 Graduate",
    description:
      "Complete all lessons, exercises, and simulation in 'Managing Your Money'",
    icon: "graduation-cap",
    unlockCondition: { type: "chapter_complete", params: { chapter: 4 } },
    isSecret: false,
    category: "Chapter",
    order: 25,
  },
  {
    name: "Chapter 5 Graduate",
    description:
      "Complete all lessons, exercises, and simulation in 'Credit & Debt'",
    icon: "graduation-cap",
    unlockCondition: { type: "chapter_complete", params: { chapter: 5 } },
    isSecret: false,
    category: "Chapter",
    order: 26,
  },
  {
    name: "Chapter 6 Graduate",
    description:
      "Complete all lessons, exercises, and simulation in 'The Shield - Fraud Protection'",
    icon: "graduation-cap",
    unlockCondition: { type: "chapter_complete", params: { chapter: 6 } },
    isSecret: false,
    category: "Chapter",
    order: 27,
  },
];
